### ISSUE TITLE
Android Fails to decode Azure Livestreams

### ISSUE THREAD

**Issue by ivo-toby** [meisterplayer/meisterplayer#38]
When android tries to play an azure livestream the blob url suddenly becomes invalid an throws a 404

**Comment by FranklinWaller** [comment]
The pipeline errors
<img width="819" alt="android error" src="https://cloud.githubusercontent.com/assets/5691892/26680626/7665b190-46da-11e7-9033-7fd2443a5096.png">
<img width="970" alt="android error 2" src="https://cloud.githubusercontent.com/assets/5691892/26680629/781c26e0-46da-11e7-816e-96c834fce51d.png">

**Comment by FranklinWaller** [comment]
Issue in GoogleIma, the implementation calls load (Which is recommended by the GoogleIma SDK) which breaks the player and makes the player fail to decode (Hence the decode pipe error). It's best to make an edge case for the load() call.

**Comment by delaet** [comment]
Is it only in combination with the Azure stream? We see the same problems with DRM content without ads.

**Comment by FranklinWaller** [comment]
@delaetthomas The issue was discovered on Azure livestreams (Hence the issue's name) and it was only found with this combination. (On our private streams the issue did not occur). I think it's best to create a new issue on the problem with DRM content without ads since GoogleIma is not involved there. (Also can you or someone else from the team) provide an URL where DRM content could not be played on Android without ads?

**Comment by FranklinWaller** [comment]
Fixed in GoogleIma v5.2.1
